#pragma once
#include "Types.h"

class Ene {
public:
    int waza_flg;
    int waza_wait;
    int waza_syu;
    int hp;
    int max_hp;
    int zoku;
    int waza_id[5];
    int waza_zoku[5];
    int pow[5];
    int zenny;
    int drop_tip[4];
    int pos_x;
    int pos_y;
    int pos_dx;
    int pos_dy;
    int tmp_x;
    int tmp_y;
    int def_x;
    int def_y;
    int move_flg;
    int move_cnt;
    int wait_cnt;
    int syoumetu_cnt;
    int on;
    int joutai;
    int muteki_cnt;
    int tmp_muteki_cnt;
    int hit_cnt;
    int ani_wait_cnt;
    int tmp_wait_cnt;
    int ani_ok;
    int s_wait;
    int e_wait;
    int r_suu;
    int r_s;
    int r_e;
    int ani_id;
    int ani_pt[3];
    int ani_max;
    int ani_cnt;
    int ani_cnt_max;
    static int move[22][5];
    int chara_no;
    int chara_lv;
    int chara_id;
    int ene_id;
    int bari;
    int bari_id;
    int ata_id;
    int han;
    int pane_id;
    int tmp_move;
    static int eria_flg;
    int tmp_cnt;
    int tmp_cnt2;
    int air;
    int tmp_lv;
    int def_ani;
    int navi_flg;
    int mahi_id;
    int muteki2;
    int t_ani_cnt;
    int tmp_s_wait;
    int tmp_r_suu;
    int tmp_e_wait;
    int x_sp;
    int y_sp;

    Ene();
    void init(int n, int n2, int n3, int n4, int n5);
    void AniSet(int n);
    void MoveSet();
    void Move();
    void PaneCh();
    int  Check(int n, int n2);
    bool Hit(int n, int n2, int n3);
    void Syoumetu();
    void EffSet(int n);
    void WazaSet();
    void Action();
    void Loop();
    void HpDraw(int n, int n2);
    void Draw(int n);
};
